###
### Display
###
# Verbose program output
verbose = true

# Show progress
progress = false


###
### Runtime
###
# Number of threads to utilize.
# Defaults to number of cores available to the system if omitted.
#threads = 2

# Maximum number of allowed redirects
max_redirects = 15


###
### Requests
###
# User agent to send with each request
user_agent = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"

# Website timeout from connect to response finished
timeout = 20

# Comma-separated list of accepted status codes for valid links.
# Omit to accept all response types.
# accept = [200, 204, 429]

# Proceed for server connections considered insecure (invalid TLS)
insecure = true

# Only test links with the given scheme (e.g. https)
# Omit to check links with any scheme
#scheme = "https"

# Request method
method = "get"

# Custom request headers
headers = []

###
### Exclusions
###
# Exclude URLs from checking (supports regex)
exclude = [
    # "github", todo github token
    "file://.*",
    "host.docker.internal:3100",
    "fileb://.*",
    "localhost",
    "example.com",
    "inmemory://",
    "github.com/marketplace/",
    "www.dreamstime.com/",
    "pixabay.com/",
    "www.pexels.com/",
    "www.publicdomainpictures.net/",
    "www.zwicon.com/",
    "els-jbs-prod-cdn.literatumonline.com/cms/attachment/",
    "wol-prod-cdn.literatumonline.com/cms/",
    "gitlab.com/api/v4/",
    "nvidia-docker.list",
    "drive.google.com/drive/",
]

# Exclude URLs contained in a file from checking
# If a file named `.lycheeignore` exists in the current working directory,
# its contents will be excluded as well.
exclude_file = []

include = []

# Exclude all private IPs from checking
# Equivalent to setting `exclude_private`, `exclude_link_local`, and `exclude_loopback` to true
exclude_all_private = false

# Exclude private IP address ranges from checking
exclude_private = false

# Exclude link-local IP address range from checking
exclude_link_local = false

# Exclude loopback IP address range from checking
exclude_loopback = true

# Exclude all mail addresses from checking
exclude_mail = false
