include:
  - project: "sosiristseng/gitlab-examples"
    file: "/hugo.gitlab-ci.yml"
  - project: "sosiristseng/gitlab-examples"
    file: "/lychee.gitlab-ci.yml"

variables:
  HUGO_BASE_URL: "https://sosiristseng.gitlab.io/readlist/"
